package test.sr.client;

import java.math.BigDecimal;
import java.util.Date;

public class ScrumData {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCRUM_DATA.SCRUM_DATA_ID
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    private Long scrumDataId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCRUM_DATA.SCRUM_DATE
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    private Date scrumDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCRUM_DATA.USER_ID
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    private Long userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCRUM_DATA.TASK
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    private String task;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCRUM_DATA.HOURS_SPENT
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    private BigDecimal hoursSpent;
    
    private Users user;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCRUM_DATA.SCRUM_DATA_ID
     *
     * @return the value of SCRUM_DATA.SCRUM_DATA_ID
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public Long getScrumDataId() {
        return scrumDataId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCRUM_DATA.SCRUM_DATA_ID
     *
     * @param scrumDataId the value for SCRUM_DATA.SCRUM_DATA_ID
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void setScrumDataId(Long scrumDataId) {
        this.scrumDataId = scrumDataId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCRUM_DATA.SCRUM_DATE
     *
     * @return the value of SCRUM_DATA.SCRUM_DATE
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public Date getScrumDate() {
        return scrumDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCRUM_DATA.SCRUM_DATE
     *
     * @param scrumDate the value for SCRUM_DATA.SCRUM_DATE
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void setScrumDate(Date scrumDate) {
        this.scrumDate = scrumDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCRUM_DATA.USER_ID
     *
     * @return the value of SCRUM_DATA.USER_ID
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCRUM_DATA.USER_ID
     *
     * @param userId the value for SCRUM_DATA.USER_ID
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCRUM_DATA.TASK
     *
     * @return the value of SCRUM_DATA.TASK
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public String getTask() {
        return task;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCRUM_DATA.TASK
     *
     * @param task the value for SCRUM_DATA.TASK
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void setTask(String task) {
        this.task = task;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCRUM_DATA.HOURS_SPENT
     *
     * @return the value of SCRUM_DATA.HOURS_SPENT
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public BigDecimal getHoursSpent() {
        return hoursSpent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCRUM_DATA.HOURS_SPENT
     *
     * @param hoursSpent the value for SCRUM_DATA.HOURS_SPENT
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void setHoursSpent(BigDecimal hoursSpent) {
        this.hoursSpent = hoursSpent;
    }

	public Users getUser()
	{
		return user;
	}

	public void setUser(Users user)
	{
		this.user = user;
	}
}