package test.sr.client;

public class Users {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column USERS.USER_ID
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    private Long userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column USERS.USERNAME
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    private String username;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column USERS.PASSWORD
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column USERS.EMAIL
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    private String email;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column USERS.USER_ID
     *
     * @return the value of USERS.USER_ID
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column USERS.USER_ID
     *
     * @param userId the value for USERS.USER_ID
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column USERS.USERNAME
     *
     * @return the value of USERS.USERNAME
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column USERS.USERNAME
     *
     * @param username the value for USERS.USERNAME
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column USERS.PASSWORD
     *
     * @return the value of USERS.PASSWORD
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column USERS.PASSWORD
     *
     * @param password the value for USERS.PASSWORD
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column USERS.EMAIL
     *
     * @return the value of USERS.EMAIL
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column USERS.EMAIL
     *
     * @param email the value for USERS.EMAIL
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void setEmail(String email) {
        this.email = email;
    }
}