package test.sr.dao;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import test.sr.client.ScrumData;

public class ScrumDataDAOImpl extends SqlMapClientDaoSupport implements ScrumDataDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public ScrumDataDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void insert(ScrumData record) {
        getSqlMapClientTemplate().insert("SCRUM_DATA.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public int updateByPrimaryKey(ScrumData record) {
        int rows = getSqlMapClientTemplate().update("SCRUM_DATA.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public int updateByPrimaryKeySelective(ScrumData record) {
        int rows = getSqlMapClientTemplate().update("SCRUM_DATA.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public ScrumData selectByPrimaryKey(Long scrumDataId) {
        ScrumData key = new ScrumData();
        key.setScrumDataId(scrumDataId);
        ScrumData record = (ScrumData) getSqlMapClientTemplate().queryForObject("SCRUM_DATA.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public int deleteByPrimaryKey(Long scrumDataId) {
        ScrumData key = new ScrumData();
        key.setScrumDataId(scrumDataId);
        int rows = getSqlMapClientTemplate().delete("SCRUM_DATA.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}