package test.sr.dao;

import test.sr.client.ScrumData;

public interface ScrumDataDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    void insert(ScrumData record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    int updateByPrimaryKey(ScrumData record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    int updateByPrimaryKeySelective(ScrumData record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    ScrumData selectByPrimaryKey(Long scrumDataId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCRUM_DATA
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    int deleteByPrimaryKey(Long scrumDataId);
}