package test.sr.dao;

import test.sr.client.Users;

public interface UsersDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    void insert(Users record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    int updateByPrimaryKey(Users record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    Users selectByPrimaryKey(Long userId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    int deleteByPrimaryKey(Long userId);
}