package test.sr.dao;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import test.sr.client.Users;

public class UsersDAOImpl extends SqlMapClientDaoSupport implements UsersDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public UsersDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public void insert(Users record) {
        getSqlMapClientTemplate().insert("USERS.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public int updateByPrimaryKey(Users record) {
        int rows = getSqlMapClientTemplate().update("USERS.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public int updateByPrimaryKeySelective(Users record) {
        int rows = getSqlMapClientTemplate().update("USERS.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public Users selectByPrimaryKey(Long userId) {
        Users key = new Users();
        key.setUserId(userId);
        Users record = (Users) getSqlMapClientTemplate().queryForObject("USERS.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USERS
     *
     * @abatorgenerated Wed Feb 25 22:31:00 IST 2009
     */
    public int deleteByPrimaryKey(Long userId) {
        Users key = new Users();
        key.setUserId(userId);
        int rows = getSqlMapClientTemplate().delete("USERS.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}